[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "balancepy"
version = "0.0.1"
authors = [
  { name="Lorenz Assländer", email="lorenz.asslaender@uni-konstanz.de" },
  { name="Matthias Albrecht", email="matthias.albrecht@uni-konstanz.de" },
]
description = "Human balance analysis using Python"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "scipy",
  "hatchling",
  "pandas",
  "ipykernel",
  "plotly",
  "nbformat",
  "openpyxl",
  "scikit-rf",
  "statsmodels",
  "joblib",
  "ipywidgets",
  "kaleido",
  "scikits-bootstrap"
]




[project.urls]
Homepage = "https://github.com/PostureControlLab/balancepy"
Issues = "https://github.com/PostureControlLab/balancepy/issues"


